version: '3.5'

services:

  db:
    image: mysql:8.0.26
    container_name: db
    ports:
      - 3306:3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=512K
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      TZ: GMT
#    volumes:
#      - "./dump.sql"
    networks:
      - blog

  db-ui:
    image: phpmyadmin/phpmyadmin
    container_name: db-ui
    ports:
      - 5678:80
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - blog

networks:
  blog:
    driver: bridge

volumes:
  blog-data:
